`timescale 1ns/1ps

module tb_core_isa;

    // Parameters
    localparam NUM_COL    = 8;
    localparam PSUM_WIDTH = 32;
    localparam SRAM_DEPTH = 8192;
    localparam INST_DEPTH = 8192;
    
    // OFM dimensions: read at runtime via +H_OUT=N +W_OUT=N plusargs
    // (generated by gen_isa_test.py into sim_params.f, passed to vsim via -f sim_params.f)

    logic clk;
    logic rst_n;
    logic start;
    logic done;
    logic signed [NUM_COL*PSUM_WIDTH-1:0] psum_out_vec;

    logic [63:0] ofb_rdata_ext;

    // Instantiate core
    core_top #(
        .NUM_COL(NUM_COL),
        .NUM_PE(8),
        .DATA_WIDTH(8),
        .PSUM_WIDTH(PSUM_WIDTH),
        .WRF_DEPTH(32),
        .ARF_DEPTH(32),
        .PARF_DEPTH(32),
        .SRAM_DEPTH(SRAM_DEPTH),
        .INST_DEPTH(INST_DEPTH)
    ) u_core_top (
        .clk(clk),
        .rst_n(rst_n),
        .start(start),
        .inst_we_ext(1'b0),
        .inst_waddr_ext('0),
        .inst_wdata_ext('0),
        .ifb_we_ext(1'b0),
        .ifb_waddr_ext('0),
        .ifb_wdata_ext('0),
        .wb_we_ext(1'b0),
        .wb_waddr_ext('0),
        .wb_wdata_ext('0),
        .ofb_re_ext(1'b0),
        .ofb_raddr_ext('0),
        .ofb_rdata_ext(ofb_rdata_ext),
        .psum_out_vec(psum_out_vec),
        .done(done)
    );

    // Clock generation
    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end

    // Load SRAMs
    initial begin
        $readmemh("inst.txt", u_core_top.u_inst_sram.mem);
        $readmemh("ifb.txt",  u_core_top.u_ifb.mem);
        $readmemh("wb.txt",   u_core_top.u_wb.mem);
        // 清空 OFB
        for (int i=0; i<SRAM_DEPTH; i++) u_core_top.u_ofb.mem[i] = '0;
    end

    // Expected OFM array
    logic [63:0] expected_ofm_arr [0:8191];

    // Cycle tracking
    longint total_cycles = 0;
    logic is_running = 0;
    always_ff @(posedge clk) begin
        if (rst_n) begin
            if (start) is_running <= 1;
            if (done) is_running <= 0;
            if (is_running) total_cycles++;
        end else begin
            total_cycles <= 0;
            is_running <= 0;
        end
    end

    // Helper arrays for hierarchical counters
    int pe_mac_cnt_arr [0:NUM_COL-1][0:7];
    int pe_wrf_write_arr [0:NUM_COL-1][0:7];
    int parf_write_arr [0:NUM_COL-1];

    genvar gc, gp;
    generate
        for (gc = 0; gc < NUM_COL; gc++) begin : perf_col
            assign parf_write_arr[gc] = u_core_top.u_mac_array.gen_col[gc].u_col.u_parf.total_write_ops;
            for (gp = 0; gp < 8; gp++) begin : perf_pe
                assign pe_mac_cnt_arr[gc][gp] = u_core_top.u_mac_array.gen_col[gc].u_col.gen_pe[gp].u_pe.mac_ops_cnt;
                assign pe_wrf_write_arr[gc][gp] = u_core_top.u_mac_array.gen_col[gc].u_col.gen_pe[gp].u_pe.u_wrf.total_write_ops;
            end
        end
    endgenerate

    // Test sequence
    initial begin
        // Watchdog Timer
        #50000000; // 50ms timeout
        $display("========================================");
        $display("FATAL ERROR: Simulation Timeout! The core likely hung in an infinite loop.");
        $display("========================================");
        $stop;
    end

    initial begin
        rst_n = 0;
        start = 0;
        #20;
        rst_n = 1;
        #10;
        
        // Load expected values
        $readmemh("expected_ofm.txt", expected_ofm_arr);
        
        $display("========================================");
        $display("Starting Macro-ISA CNN Core...");
        $display("========================================");
        
        start = 1;
        #10;
        start = 0;

        // Wait for done flag
        wait(done == 1);
        #50;

        $display("========================================");
        $display("Macro-ISA Core Execution Finished.");
        $display("Checking Outmap Buffer (OFB) computed results...");
        
        begin
            // Count total mismatches
            automatic int mismatch_cnt = 0;
            
            // Verify all expected output pixels
            // Read OFM dimensions from plusargs (set by gen_isa_test.py via sim_params.f)
            int h_out_val, w_out_val, total_ofm;
            if (!$value$plusargs("H_OUT=%d", h_out_val)) h_out_val = 121;
            if (!$value$plusargs("W_OUT=%d", w_out_val)) w_out_val = 43;
            total_ofm = h_out_val * w_out_val;
            $display("OFM dimensions: H_OUT=%0d, W_OUT=%0d, TOTAL=%0d", h_out_val, w_out_val, total_ofm);

            for (int addr = 0; addr < total_ofm; addr++) begin
                automatic logic [63:0] actual = u_core_top.u_ofb.mem[addr];
                automatic logic [63:0] expected = expected_ofm_arr[addr];
                
                if (actual !== expected) begin
                    if (mismatch_cnt < 10) begin
                        $display("FAIL: OFB[%0d] | Expected: %016x, Got: %016x", addr, expected, actual);
                    end
                    if (mismatch_cnt == 10) begin
                        $display("... (Further mismatches suppressed)");
                    end
                    mismatch_cnt++;
                end
            end
            
            if (mismatch_cnt == 0) begin
                $display("Check Complete! 0 mismatches found. 2D ISA simulation passed successfully.");
            end else begin
                $display("Check Complete! Found %0d mismatches. Simulation FAILED.", mismatch_cnt);
            end
            
            $display("========================================");
            $display(" PERFORMANCE & RESOURCE UTILIZATION STATS");
            $display("========================================");
            $display("Total Active Cycles:  %0d", total_cycles);
            $display("");
            $display("--- SRAM Traffic ---");
            $display("IFB (Input Data):     Reads = %0d, Writes = %0d", u_core_top.u_ifb.sram_read_cnt, u_core_top.u_ifb.sram_write_cnt);
            $display("WB  (Weight Data):    Reads = %0d, Writes = %0d", u_core_top.u_wb.sram_read_cnt,  u_core_top.u_wb.sram_write_cnt);
            $display("OFB (Output Data):    Reads = %0d, Writes = %0d", u_core_top.u_ofb.sram_read_cnt, u_core_top.u_ofb.sram_write_cnt);
            $display("");
            
            begin
                longint total_mac_ops = 0;
                longint total_wrf_writes = 0;
                longint total_parf_writes = 0;
                
                for (int c = 0; c < NUM_COL; c++) begin
                    for (int p = 0; p < 8; p++) begin
                        total_mac_ops    += pe_mac_cnt_arr[c][p];
                        total_wrf_writes += pe_wrf_write_arr[c][p];
                    end
                    total_parf_writes += parf_write_arr[c];
                end
                
                $display("--- PE Array Utilization ---");
                $display("Total MAC Ops:        %0d ops", total_mac_ops);
                $display("Theoretical Max MACs: %0d ops (Total Cycles * 64 PEs)", total_cycles * 64);
                $display("MAC Utilization Rate: %.2f %%", (real'(total_mac_ops) / (real'(total_cycles) * 64.0)) * 100.0);
                $display("");
                $display("--- Register File Traffic ---");
                $display("ARF  Writes (SRAM Load):   %0d", u_core_top.u_arf.total_write_ops);
                $display("ARF  Reads  (To MAC):      %0d (Combinational read matching MAC active cycles)", total_mac_ops / 64);
                $display("WRF  Writes (Weights):     %0d", total_wrf_writes);
                $display("PARF Writes (Psum Accum):  %0d", total_parf_writes);
            end
        end
        $display("========================================");
        $stop;
    end

endmodule