`timescale 1ns/1ps

// =============================================================================
// multicore_top_vd100_bd_v.v  --  Verilog wrapper for SV BD module
//
// Vivado BD `create_bd_cell -type module -reference` 不接受 SystemVerilog 顶层.
// 这个 .v wrapper 用纯 Verilog (wire/reg) 包装 multicore_top_vd100_bd (SV), 让
// BD 能识别. SV 的 X_INTERFACE_INFO attribute 通过 Verilog (* ... *) syntax 重写
// 在这个 wrapper 上.
//
// 端口签名 1:1 对应 multicore_top_vd100_bd.sv 的端口.
// =============================================================================

(* CORE_GENERATION_INFO = "multicore_top_vd100_bd_v,multicore_top_vd100_bd,{NUM_CORES=3}" *)
module multicore_top_vd100_bd_v (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF csr_axil:m00_axi:m01_axi:m02_axi, ASSOCIATED_RESET rst_n" *)
    input                clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 rst_n RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input                rst_n,

    // CSR AXI-Lite slave
    (* X_INTERFACE_PARAMETER = "MODE Slave, ADDR_WIDTH 14, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1" *)
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil AWADDR" *)  input  [13:0] csr_axil_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil AWVALID" *) input         csr_axil_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil AWREADY" *) output        csr_axil_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil WDATA" *)   input  [31:0] csr_axil_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil WSTRB" *)   input  [3:0]  csr_axil_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil WVALID" *)  input         csr_axil_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil WREADY" *)  output        csr_axil_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil BRESP" *)   output [1:0]  csr_axil_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil BVALID" *)  output        csr_axil_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil BREADY" *)  input         csr_axil_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil ARADDR" *)  input  [13:0] csr_axil_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil ARVALID" *) input         csr_axil_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil ARREADY" *) output        csr_axil_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil RDATA" *)   output [31:0] csr_axil_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil RRESP" *)   output [1:0]  csr_axil_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil RVALID" *)  output        csr_axil_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 csr_axil RREADY" *)  input         csr_axil_rready,

    // M00_AXI master (Core 0)
    // VD100 fix 2026-05-13: 声明 m0X_axi master capability 让 axi_noc S0X_AXI 正确 infer.
    // axi_dm IP 单 thread 同 ID 多 cmd, axi_noc 默认 multi-thread 假设可能让 R/B 路由错位.
    (* X_INTERFACE_PARAMETER = "MODE Master, PROTOCOL AXI4, ADDR_WIDTH 32, DATA_WIDTH 128, ID_WIDTH 5, FREQ_HZ 100000000, NUM_WRITE_OUTSTANDING 1, NUM_WRITE_THREADS 1, NUM_READ_OUTSTANDING 1, NUM_READ_THREADS 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0" *)
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWID" *)    output [4:0]   m00_axi_awid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWADDR" *)  output [31:0]  m00_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWLEN" *)   output [7:0]   m00_axi_awlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWSIZE" *)  output [2:0]   m00_axi_awsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWBURST" *) output [1:0]   m00_axi_awburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWLOCK" *)  output         m00_axi_awlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWCACHE" *) output [3:0]   m00_axi_awcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWPROT" *)  output [2:0]   m00_axi_awprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWQOS" *)   output [3:0]   m00_axi_awqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWVALID" *) output         m00_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi AWREADY" *) input          m00_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi WDATA" *)   output [127:0] m00_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi WSTRB" *)   output [15:0]  m00_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi WLAST" *)   output         m00_axi_wlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi WVALID" *)  output         m00_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi WREADY" *)  input          m00_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi BID" *)     input  [4:0]   m00_axi_bid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi BRESP" *)   input  [1:0]   m00_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi BVALID" *)  input          m00_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi BREADY" *)  output         m00_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARID" *)    output [4:0]   m00_axi_arid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARADDR" *)  output [31:0]  m00_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARLEN" *)   output [7:0]   m00_axi_arlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARSIZE" *)  output [2:0]   m00_axi_arsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARBURST" *) output [1:0]   m00_axi_arburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARLOCK" *)  output         m00_axi_arlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARCACHE" *) output [3:0]   m00_axi_arcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARPROT" *)  output [2:0]   m00_axi_arprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARQOS" *)   output [3:0]   m00_axi_arqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARVALID" *) output         m00_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi ARREADY" *) input          m00_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RID" *)     input  [4:0]   m00_axi_rid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RDATA" *)   input  [127:0] m00_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RRESP" *)   input  [1:0]   m00_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RLAST" *)   input          m00_axi_rlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RVALID" *)  input          m00_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m00_axi RREADY" *)  output         m00_axi_rready,

    // M01_AXI master (Core 1)
    (* X_INTERFACE_PARAMETER = "MODE Master, PROTOCOL AXI4, ADDR_WIDTH 32, DATA_WIDTH 128, ID_WIDTH 5, FREQ_HZ 100000000, NUM_WRITE_OUTSTANDING 1, NUM_WRITE_THREADS 1, NUM_READ_OUTSTANDING 1, NUM_READ_THREADS 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0" *)
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWID" *)    output [4:0]   m01_axi_awid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWADDR" *)  output [31:0]  m01_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWLEN" *)   output [7:0]   m01_axi_awlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWSIZE" *)  output [2:0]   m01_axi_awsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWBURST" *) output [1:0]   m01_axi_awburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWLOCK" *)  output         m01_axi_awlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWCACHE" *) output [3:0]   m01_axi_awcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWPROT" *)  output [2:0]   m01_axi_awprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWQOS" *)   output [3:0]   m01_axi_awqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWVALID" *) output         m01_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi AWREADY" *) input          m01_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi WDATA" *)   output [127:0] m01_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi WSTRB" *)   output [15:0]  m01_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi WLAST" *)   output         m01_axi_wlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi WVALID" *)  output         m01_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi WREADY" *)  input          m01_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi BID" *)     input  [4:0]   m01_axi_bid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi BRESP" *)   input  [1:0]   m01_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi BVALID" *)  input          m01_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi BREADY" *)  output         m01_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARID" *)    output [4:0]   m01_axi_arid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARADDR" *)  output [31:0]  m01_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARLEN" *)   output [7:0]   m01_axi_arlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARSIZE" *)  output [2:0]   m01_axi_arsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARBURST" *) output [1:0]   m01_axi_arburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARLOCK" *)  output         m01_axi_arlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARCACHE" *) output [3:0]   m01_axi_arcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARPROT" *)  output [2:0]   m01_axi_arprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARQOS" *)   output [3:0]   m01_axi_arqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARVALID" *) output         m01_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi ARREADY" *) input          m01_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RID" *)     input  [4:0]   m01_axi_rid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RDATA" *)   input  [127:0] m01_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RRESP" *)   input  [1:0]   m01_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RLAST" *)   input          m01_axi_rlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RVALID" *)  input          m01_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m01_axi RREADY" *)  output         m01_axi_rready,

    // M02_AXI master (Core 2)
    (* X_INTERFACE_PARAMETER = "MODE Master, PROTOCOL AXI4, ADDR_WIDTH 32, DATA_WIDTH 128, ID_WIDTH 5, FREQ_HZ 100000000, NUM_WRITE_OUTSTANDING 1, NUM_WRITE_THREADS 1, NUM_READ_OUTSTANDING 1, NUM_READ_THREADS 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 256, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0" *)
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWID" *)    output [4:0]   m02_axi_awid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWADDR" *)  output [31:0]  m02_axi_awaddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWLEN" *)   output [7:0]   m02_axi_awlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWSIZE" *)  output [2:0]   m02_axi_awsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWBURST" *) output [1:0]   m02_axi_awburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWLOCK" *)  output         m02_axi_awlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWCACHE" *) output [3:0]   m02_axi_awcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWPROT" *)  output [2:0]   m02_axi_awprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWQOS" *)   output [3:0]   m02_axi_awqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWVALID" *) output         m02_axi_awvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi AWREADY" *) input          m02_axi_awready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi WDATA" *)   output [127:0] m02_axi_wdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi WSTRB" *)   output [15:0]  m02_axi_wstrb,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi WLAST" *)   output         m02_axi_wlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi WVALID" *)  output         m02_axi_wvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi WREADY" *)  input          m02_axi_wready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi BID" *)     input  [4:0]   m02_axi_bid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi BRESP" *)   input  [1:0]   m02_axi_bresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi BVALID" *)  input          m02_axi_bvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi BREADY" *)  output         m02_axi_bready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARID" *)    output [4:0]   m02_axi_arid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARADDR" *)  output [31:0]  m02_axi_araddr,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARLEN" *)   output [7:0]   m02_axi_arlen,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARSIZE" *)  output [2:0]   m02_axi_arsize,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARBURST" *) output [1:0]   m02_axi_arburst,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARLOCK" *)  output         m02_axi_arlock,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARCACHE" *) output [3:0]   m02_axi_arcache,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARPROT" *)  output [2:0]   m02_axi_arprot,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARQOS" *)   output [3:0]   m02_axi_arqos,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARVALID" *) output         m02_axi_arvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi ARREADY" *) input          m02_axi_arready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RID" *)     input  [4:0]   m02_axi_rid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RDATA" *)   input  [127:0] m02_axi_rdata,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RRESP" *)   input  [1:0]   m02_axi_rresp,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RLAST" *)   input          m02_axi_rlast,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RVALID" *)  input          m02_axi_rvalid,
    (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 m02_axi RREADY" *)  output         m02_axi_rready,

    // IRQ output
    (* X_INTERFACE_INFO = "xilinx.com:signal:interrupt:1.0 irq_done INTERRUPT" *)
    output [2:0]         irq_done,

    // Debug expose (BD 端 axis_ila 接 probes)
    output               dbg_awvalid_0,
    output               dbg_awready_0,
    output               dbg_arvalid_0,
    output               dbg_arready_0,
    output               dbg_wvalid_0,
    output               dbg_rvalid_0,
    output [31:0]        dbg_awaddr_0,
    output [31:0]        dbg_araddr_0,
    output [3:0]         dbg_awid_0,
    output [3:0]         dbg_arid_0,
    output [7:0]         dbg_awlen_0,
    output [7:0]         dbg_arlen_0,
    output [1:0]         dbg_dfe_state_0,
    output               dbg_dfe_m_arvalid_0,
    output               dbg_dfe_m_arready_0,
    output               dbg_dfe_r_phase_0,
    output               dbg_dfe_r_done_0,
    output [15:0]        dbg_dfe_r_beats_rcvd_0,
    output               dbg_arb_rd_lock_0,
    output [1:0]         dbg_arb_rd_sel_0,
    output [1:0]         dbg_arb_cu_rd_sel_0,
    output [3:0]         dbg_master_arvalid_0,
    output [3:0]         dbg_master_arready_0,
    output [3:0]         dbg_master_rvalid_0,
    output               dbg_start_dfe_pulse_0,
    output               dbg_dfe_busy_0,
    output               dbg_dfe_done_0,
    output               dbg_idma_busy_0,
    output               dbg_layer_busy_0,
    output               dbg_csr_aw_fire_0
);

    // 内部 instance SV module (Verilog 接受 SV module 当 black-box 实例化)
    multicore_top_vd100_bd u_inner (
        .clk(clk), .rst_n(rst_n),

        .csr_axil_awaddr(csr_axil_awaddr),   .csr_axil_awvalid(csr_axil_awvalid),
        .csr_axil_awready(csr_axil_awready), .csr_axil_wdata(csr_axil_wdata),
        .csr_axil_wstrb(csr_axil_wstrb),     .csr_axil_wvalid(csr_axil_wvalid),
        .csr_axil_wready(csr_axil_wready),   .csr_axil_bresp(csr_axil_bresp),
        .csr_axil_bvalid(csr_axil_bvalid),   .csr_axil_bready(csr_axil_bready),
        .csr_axil_araddr(csr_axil_araddr),   .csr_axil_arvalid(csr_axil_arvalid),
        .csr_axil_arready(csr_axil_arready), .csr_axil_rdata(csr_axil_rdata),
        .csr_axil_rresp(csr_axil_rresp),     .csr_axil_rvalid(csr_axil_rvalid),
        .csr_axil_rready(csr_axil_rready),

        .m00_axi_awid(m00_axi_awid),       .m00_axi_awaddr(m00_axi_awaddr),
        .m00_axi_awlen(m00_axi_awlen),     .m00_axi_awsize(m00_axi_awsize),
        .m00_axi_awburst(m00_axi_awburst), .m00_axi_awlock(m00_axi_awlock),
        .m00_axi_awcache(m00_axi_awcache), .m00_axi_awprot(m00_axi_awprot),
        .m00_axi_awqos(m00_axi_awqos),     .m00_axi_awvalid(m00_axi_awvalid),
        .m00_axi_awready(m00_axi_awready), .m00_axi_wdata(m00_axi_wdata),
        .m00_axi_wstrb(m00_axi_wstrb),     .m00_axi_wlast(m00_axi_wlast),
        .m00_axi_wvalid(m00_axi_wvalid),   .m00_axi_wready(m00_axi_wready),
        .m00_axi_bid(m00_axi_bid),         .m00_axi_bresp(m00_axi_bresp),
        .m00_axi_bvalid(m00_axi_bvalid),   .m00_axi_bready(m00_axi_bready),
        .m00_axi_arid(m00_axi_arid),       .m00_axi_araddr(m00_axi_araddr),
        .m00_axi_arlen(m00_axi_arlen),     .m00_axi_arsize(m00_axi_arsize),
        .m00_axi_arburst(m00_axi_arburst), .m00_axi_arlock(m00_axi_arlock),
        .m00_axi_arcache(m00_axi_arcache), .m00_axi_arprot(m00_axi_arprot),
        .m00_axi_arqos(m00_axi_arqos),     .m00_axi_arvalid(m00_axi_arvalid),
        .m00_axi_arready(m00_axi_arready), .m00_axi_rid(m00_axi_rid),
        .m00_axi_rdata(m00_axi_rdata),     .m00_axi_rresp(m00_axi_rresp),
        .m00_axi_rlast(m00_axi_rlast),     .m00_axi_rvalid(m00_axi_rvalid),
        .m00_axi_rready(m00_axi_rready),

        .m01_axi_awid(m01_axi_awid),       .m01_axi_awaddr(m01_axi_awaddr),
        .m01_axi_awlen(m01_axi_awlen),     .m01_axi_awsize(m01_axi_awsize),
        .m01_axi_awburst(m01_axi_awburst), .m01_axi_awlock(m01_axi_awlock),
        .m01_axi_awcache(m01_axi_awcache), .m01_axi_awprot(m01_axi_awprot),
        .m01_axi_awqos(m01_axi_awqos),     .m01_axi_awvalid(m01_axi_awvalid),
        .m01_axi_awready(m01_axi_awready), .m01_axi_wdata(m01_axi_wdata),
        .m01_axi_wstrb(m01_axi_wstrb),     .m01_axi_wlast(m01_axi_wlast),
        .m01_axi_wvalid(m01_axi_wvalid),   .m01_axi_wready(m01_axi_wready),
        .m01_axi_bid(m01_axi_bid),         .m01_axi_bresp(m01_axi_bresp),
        .m01_axi_bvalid(m01_axi_bvalid),   .m01_axi_bready(m01_axi_bready),
        .m01_axi_arid(m01_axi_arid),       .m01_axi_araddr(m01_axi_araddr),
        .m01_axi_arlen(m01_axi_arlen),     .m01_axi_arsize(m01_axi_arsize),
        .m01_axi_arburst(m01_axi_arburst), .m01_axi_arlock(m01_axi_arlock),
        .m01_axi_arcache(m01_axi_arcache), .m01_axi_arprot(m01_axi_arprot),
        .m01_axi_arqos(m01_axi_arqos),     .m01_axi_arvalid(m01_axi_arvalid),
        .m01_axi_arready(m01_axi_arready), .m01_axi_rid(m01_axi_rid),
        .m01_axi_rdata(m01_axi_rdata),     .m01_axi_rresp(m01_axi_rresp),
        .m01_axi_rlast(m01_axi_rlast),     .m01_axi_rvalid(m01_axi_rvalid),
        .m01_axi_rready(m01_axi_rready),

        .m02_axi_awid(m02_axi_awid),       .m02_axi_awaddr(m02_axi_awaddr),
        .m02_axi_awlen(m02_axi_awlen),     .m02_axi_awsize(m02_axi_awsize),
        .m02_axi_awburst(m02_axi_awburst), .m02_axi_awlock(m02_axi_awlock),
        .m02_axi_awcache(m02_axi_awcache), .m02_axi_awprot(m02_axi_awprot),
        .m02_axi_awqos(m02_axi_awqos),     .m02_axi_awvalid(m02_axi_awvalid),
        .m02_axi_awready(m02_axi_awready), .m02_axi_wdata(m02_axi_wdata),
        .m02_axi_wstrb(m02_axi_wstrb),     .m02_axi_wlast(m02_axi_wlast),
        .m02_axi_wvalid(m02_axi_wvalid),   .m02_axi_wready(m02_axi_wready),
        .m02_axi_bid(m02_axi_bid),         .m02_axi_bresp(m02_axi_bresp),
        .m02_axi_bvalid(m02_axi_bvalid),   .m02_axi_bready(m02_axi_bready),
        .m02_axi_arid(m02_axi_arid),       .m02_axi_araddr(m02_axi_araddr),
        .m02_axi_arlen(m02_axi_arlen),     .m02_axi_arsize(m02_axi_arsize),
        .m02_axi_arburst(m02_axi_arburst), .m02_axi_arlock(m02_axi_arlock),
        .m02_axi_arcache(m02_axi_arcache), .m02_axi_arprot(m02_axi_arprot),
        .m02_axi_arqos(m02_axi_arqos),     .m02_axi_arvalid(m02_axi_arvalid),
        .m02_axi_arready(m02_axi_arready), .m02_axi_rid(m02_axi_rid),
        .m02_axi_rdata(m02_axi_rdata),     .m02_axi_rresp(m02_axi_rresp),
        .m02_axi_rlast(m02_axi_rlast),     .m02_axi_rvalid(m02_axi_rvalid),
        .m02_axi_rready(m02_axi_rready),

        .irq_done(irq_done),
        // Debug
        .dbg_awvalid_0(dbg_awvalid_0), .dbg_awready_0(dbg_awready_0),
        .dbg_arvalid_0(dbg_arvalid_0), .dbg_arready_0(dbg_arready_0),
        .dbg_wvalid_0(dbg_wvalid_0),   .dbg_rvalid_0(dbg_rvalid_0),
        .dbg_awaddr_0(dbg_awaddr_0),   .dbg_araddr_0(dbg_araddr_0),
        .dbg_awid_0(dbg_awid_0),       .dbg_arid_0(dbg_arid_0),
        .dbg_awlen_0(dbg_awlen_0),     .dbg_arlen_0(dbg_arlen_0),
        .dbg_dfe_state_0(dbg_dfe_state_0),
        .dbg_dfe_m_arvalid_0(dbg_dfe_m_arvalid_0),
        .dbg_dfe_m_arready_0(dbg_dfe_m_arready_0),
        .dbg_dfe_r_phase_0(dbg_dfe_r_phase_0),
        .dbg_dfe_r_done_0(dbg_dfe_r_done_0),
        .dbg_dfe_r_beats_rcvd_0(dbg_dfe_r_beats_rcvd_0),
        .dbg_arb_rd_lock_0(dbg_arb_rd_lock_0),
        .dbg_arb_rd_sel_0(dbg_arb_rd_sel_0),
        .dbg_arb_cu_rd_sel_0(dbg_arb_cu_rd_sel_0),
        .dbg_master_arvalid_0(dbg_master_arvalid_0),
        .dbg_master_arready_0(dbg_master_arready_0),
        .dbg_master_rvalid_0(dbg_master_rvalid_0),
        .dbg_start_dfe_pulse_0(dbg_start_dfe_pulse_0),
        .dbg_dfe_busy_0(dbg_dfe_busy_0),
        .dbg_dfe_done_0(dbg_dfe_done_0),
        .dbg_idma_busy_0(dbg_idma_busy_0),
        .dbg_layer_busy_0(dbg_layer_busy_0),
        .dbg_csr_aw_fire_0(dbg_csr_aw_fire_0)
    );

endmodule
