"""
mesh_cmd.py  --  Mesh 模式 driver: per-(mem, layer) Mem core desc list 生成 + 文件格式

设计目标
========
mesh 模式下每核 mem (= mesh y=0 row 的 stub) 是 ConvCore 的 IFB 数据源:
  - 每层 ConvCore[c] cfg_skip_idma=1, IFB 等 mem[c] 推
  - mem[c] 把 DDR 内的 IFB 数据按 row 切, 一行一个 packet 经 mesh 发给 ConvCore[c]

[Step F.4 优化] mem 内置 desc engine (类比 ConvCore 的 dfe.sv):
  - host 把 desc list preload 到 mem.ddr_mem 某区域
  - host 写 mem CSR: DESC_LIST_ADDR / DESC_COUNT / start_pulse
  - mem desc engine 自动从 ddr_mem 拉 desc, 顺序 trigger axis_packet_tx
  - 4 个 mem 真并行 (host CSR 总线只写 3 个寄存器/层, 不再 per-cmd 串行)

二进制 desc 格式 (16 byte = 128 bit / 1 ddr_mem word, NHWC layout 兼容):
  bit [31:0]    ddr_addr_w     mem.ddr_mem 内 word offset (读起点)
  bit [47:32]   burst_len      packet beat 数
  bit [79:48]   sram_offset_w  packet header 里的 sram offset (32-bit, 实际 20-bit 用)
                                stub 限制 == ddr_addr_w
  bit [87:80]   tdest          8-bit, [7:4]=dst_y [3:0]=dst_x
  bit [91:88]   opcode         4-bit
  bit [127:92]  reserved       36-bit, 0

opcode:
  0x0 = WRITE_IFB        (mem → ConvCore: 推 IFB row)
  0x5 = WRITE_DDR_OFB    (ConvCore → mem: 出 OFM, 由 ConvCore 端 axi_writer_to_axis 用)

tdest:
  ConvCore[c] @ (x=c, y=1) → tdest = 0x10 | c
  Mem[c]      @ (x=c, y=0) → tdest = 0x00 | c

per-(mem, layer) 文件命名: ``mem{m}_layer{l:02d}_descs.hex``
  每行一个 16-byte desc (32 hex char), TB 用 $readmemh 加载.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import List, Optional


# ============================================================================
# tdest / opcode 常量
# ============================================================================
def conv_core_tdest(core_id: int) -> int:
    """ConvCore[c] @ (x=c, y=1) → tdest 8-bit"""
    return (1 << 4) | (core_id & 0xF)


def mem_core_tdest(core_id: int) -> int:
    """Mem[c] @ (x=c, y=0) → tdest 8-bit"""
    return (0 << 4) | (core_id & 0xF)


# Opcode (mesh packet header bits [127:124])
OPCODE_WRITE_IFB     = 0x0   # mem → ConvCore: 写 ConvCore.IFB SRAM
OPCODE_READ_DDR      = 0x1   # 暂未用
OPCODE_WRITE_DDR_OFB = 0x5   # ConvCore → mem: 写 mem.ddr_mem (OFM 区), axi_writer_to_axis 出


# ============================================================================
# cmd 数据结构
# ============================================================================
@dataclass
class MemCmd:
    """一条 mem core packet 推送 cmd (对应一个 mesh packet)."""
    ddr_addr_w:    int     # mem.ddr_mem 内 word offset (读起点)
    burst_len:     int     # packet beat 数
    sram_offset_w: int     # packet header 里的 sram offset (接收端 SRAM 写入位置)
                            # stub 限制: 必须 == ddr_addr_w
    tdest:         int     # 8-bit
    opcode:        int     # 4-bit
    name:          str = ""

    def __post_init__(self):
        if self.sram_offset_w != self.ddr_addr_w:
            raise ValueError(
                f"stub 限制: sram_offset_w({self.sram_offset_w}) "
                f"必须 == ddr_addr_w({self.ddr_addr_w}) [{self.name}]"
            )

    def to_hex_line(self) -> str:
        """二进制 desc 编码 (16 byte = 32 hex char) — 给 mem desc engine 自动消费.
        bit [31:0]   ddr_addr_w
        bit [47:32]  burst_len
        bit [79:48]  sram_offset_w
        bit [87:80]  tdest
        bit [91:88]  opcode
        bit [127:92] reserved (36-bit, 0)
        """
        word = (
            (self.ddr_addr_w    & 0xFFFFFFFF)         |
            ((self.burst_len    & 0xFFFF)     << 32)  |
            ((self.sram_offset_w & 0xFFFFFFFF) << 48) |
            ((self.tdest        & 0xFF)       << 80)  |
            ((self.opcode       & 0xF)        << 88)
        )
        return f"{word:032x}"


# ============================================================================
# 写文件 / 读文件
# ============================================================================
def write_mem_desc_list(out_path: str, cmds: List[MemCmd], header_lines: List[str] = None) -> int:
    """写 desc list 到 out_path (二进制 hex, $readmemh 兼容). 返回 desc 数.

    每行一个 16-byte desc (32 hex char), 注释以 // 开头.
    """
    with open(out_path, 'w') as f:
        f.write("// mem desc list (auto-generated by mesh_cmd.py, $readmemh format)\n")
        if header_lines:
            for line in header_lines:
                f.write(f"// {line}\n")
        f.write(f"// n_descs = {len(cmds)}\n")
        for c in cmds:
            f.write(c.to_hex_line())
            if c.name:
                f.write(f"  // {c.name}")
            f.write("\n")
    return len(cmds)


# ============================================================================
# 高层: 给一个 (mem, layer) 生成 IFB push cmd 序列
# ============================================================================
def gen_mem_ifb_push_cmds(
    *,
    mem_id:           int,        # 哪个 mem core (= 哪个 ConvCore)
    target_core_id:   int,        # 推送目标 ConvCore (一般 == mem_id)
    h_in:             int,        # 该层输入 H (整图)
    w_in:             int,        # 该层输入 W (整图)
    cin_slices:       int,        # cin / 16
    ifb_ddr_addr_w:   int,        # mem.ddr_mem 内该层 IFB 起点 (word offset)
    ifb_sram_base_w:  int = 0,    # ConvCore IFB SRAM 起始 word offset (一般 0)
    name_prefix:      str = "",
) -> List[MemCmd]:
    """
    生成 layer 的 IFB row-by-row push cmd 序列.
    IFB layout 假设 NHWC: row r 起点 = ifb_ddr_addr_w + r * (w_in * cin_slices)

    stub 限制: sram_offset_w 必须 == ddr_addr_w, 所以 ConvCore 写入 IFB SRAM
    的位置直接复用 DDR addr (即 ConvCore 读 IFB SRAM 时也按这个 layout 算).
    实际 deployment ConvCore 端的 IFB SRAM addr 是相对的 (从 IFB ring base 0 开始
    + ring 模式自动 wrap), stub 限制下我们让 ifb_ddr_addr_w 作为整层 IFB 起点
    (= 0 通常即可); ConvCore 内部 IFB ring 用 cfg_ifb_strip_rows / ring_words
    控制 wrap.

    返回 cmd list, 每行一个 IFB row.
    """
    if ifb_sram_base_w != 0:
        # stub 限制 sram_offset == ddr_addr, 不允许 SRAM base shift
        raise NotImplementedError(
            "stub 不支持 IFB SRAM base ≠ 0; ConvCore IFB ring 起点必须 0"
        )

    row_words = w_in * cin_slices
    cmds: List[MemCmd] = []
    tdest = conv_core_tdest(target_core_id)
    for r in range(h_in):
        addr_w = ifb_ddr_addr_w + r * row_words
        cmds.append(MemCmd(
            ddr_addr_w    = addr_w,
            burst_len     = row_words,
            sram_offset_w = addr_w,    # stub 限制
            tdest         = tdest,
            opcode        = OPCODE_WRITE_IFB,
            name          = f"{name_prefix}row{r}",
        ))
    return cmds


@dataclass
class SgCmd:
    """[Phase 7 SMC + NUMA] SG (Scatter-Gather) cmd, 描述一次 axi master burst.

    跟 idma_sg_dispatcher.sv 内部解码格式对齐 (32 byte = 2 beats × 128-bit):
      word 0:  src_addr     [31:0]   transfer 起点 byte (全局地址)
      word 1:  btt          [22:0]   transfer 长度 byte
               last_cmd     [23]     1 = list 末尾
               reserved     [31:24]  0
      word 2:  sram_offset  [31:0]   IFB SRAM 写起点 (word offset)
      word 3:  reserved
    """
    src_addr:    int        # 全局地址 byte (跨 mem 边界由 SmartConnect 路由)
    btt:         int        # transfer 长度 byte (单 burst, 不跨 axi slave)
    sram_offset: int        # IFB SRAM 内 word offset
    last_cmd:    bool = False
    name:        str = ""

    def to_hex_lines(self) -> list:
        """编码成 2 行 hex (每行 16 byte = 32 hex char), 跟 $readmemh 兼容."""
        # beat 0: word 0 (src_addr) | word 1 (btt | last_cmd) | word 2 (sram_offset, 后面对齐处理)
        # 16 byte = 128 bit, 装 4 个 32-bit word
        # beat 0: [127:0] = {word3 (reserved), word2 (sram_offset), word1 (btt|last), word0 (src_addr)}
        # beat 1: 全 reserved (留给未来扩展)
        word0 = self.src_addr & 0xFFFFFFFF
        word1 = (self.btt & 0x7FFFFF) | ((1 << 23) if self.last_cmd else 0)
        word2 = self.sram_offset & 0xFFFFFFFF
        word3 = 0
        beat0 = (word0) | (word1 << 32) | (word2 << 64) | (word3 << 96)
        beat1 = 0    # reserved 16 byte
        return [f"{beat0:032x}", f"{beat1:032x}"]


def gen_idma_sg_cmd_list_w_slice(
    *,
    target_core_id:    int,                 # ConvCore[c]
    h_in:              int,                 # 该层 IFM 总行数
    cin_slices:        int,                 # cin / 16
    w_in_lo:           int,                 # 该核需要的 IFM W 起点列 (含左 halo, 整图坐标)
    w_in_hi:           int,                 # 该核需要的 IFM W 终点列 (含右 halo, 整图坐标, 闭区间)
    seg_w_starts:      list,                # 每段在整图 W 的起点列 [w0, w1, ..., w_n-1]
    seg_mem_bases:     list,                # 每段在 mem 内的全局地址 base (byte) [base0, base1, ...]
    seg_widths:        list,                # 每段宽度 (列) [w_per_mem, ...]
    ifb_ring_words:    int = 0,             # IFB SRAM ring word 数 (driver 算的 cfg_ifb_ring_words);
                                             #   cmd.sram_offset 在 ring 内 wrap. 0 = 不 wrap (整图装下)
) -> list:
    """
    生成 ConvCore[c] 的 IDMA SG cmd list (W slice 紧凑 + 跨 mem halo 拉取).

    每行 IFM 拆成多条 cmd: 每条在一个 mem 内的连续 burst.
    跨 mem 边界时多条 cmd. 物理 halo 列只一份 (driver 编译期确保 layout 无重复).

    seg_* 数组描述整图 W 段散布: 段 i 在整图 W 列 [seg_w_starts[i], seg_w_starts[i]+seg_widths[i]),
    物理在 mem[i].ddr_mem 内全局地址 seg_mem_bases[i] 起.
    """
    n_segs = len(seg_w_starts)
    assert len(seg_mem_bases) == n_segs and len(seg_widths) == n_segs

    cmds = []
    sram_offset = 0
    for r in range(h_in):
        # 该核该行需要 IFM W[w_in_lo .. w_in_hi]
        cur_w = w_in_lo
        while cur_w <= w_in_hi:
            # 找当前列在哪段
            seg_id = -1
            for s in range(n_segs):
                if seg_w_starts[s] <= cur_w < seg_w_starts[s] + seg_widths[s]:
                    seg_id = s
                    break
            if seg_id < 0:
                raise ValueError(f"col w={cur_w} not in any segment")

            seg_w_end = seg_w_starts[seg_id] + seg_widths[seg_id] - 1
            # 该段内本核拉的列范围 [cur_w, min(w_in_hi, seg_w_end)]
            chunk_lo = cur_w
            chunk_hi = min(w_in_hi, seg_w_end)
            chunk_cols = chunk_hi - chunk_lo + 1

            # 该 chunk 在该段 mem 内的 byte offset
            #   段内 layout: row r 的 col w_local 起点 = base + r * seg_w × cin_slices × 16 + w_local × cin_slices × 16
            seg_w = seg_widths[seg_id]
            w_local_lo = chunk_lo - seg_w_starts[seg_id]
            byte_addr = (seg_mem_bases[seg_id]
                         + r * seg_w * cin_slices * 16
                         + w_local_lo * cin_slices * 16)
            chunk_btt = chunk_cols * cin_slices * 16

            # ring wrap: cmd.sram_offset 必须 mod ring_words 跟 dispatcher 内 wrap 同步
            sram_offset_eff = (sram_offset % ifb_ring_words) if ifb_ring_words > 0 else sram_offset
            cmds.append(SgCmd(
                src_addr    = byte_addr,
                btt         = chunk_btt,
                sram_offset = sram_offset_eff,
                last_cmd    = False,    # 后面 patch 最后一条
                name        = f"r{r}_w[{chunk_lo}:{chunk_hi+1}]_seg{seg_id}",
            ))
            sram_offset += chunk_cols * cin_slices
            cur_w = chunk_hi + 1

    # patch 最后一条 last_cmd flag
    if cmds:
        cmds[-1].last_cmd = True
    return cmds


def write_sg_cmd_list(out_path: str, cmds: list, header_lines: list = None) -> int:
    """写 SG cmd list 到 .hex 文件 (每条 cmd 2 行, $readmemh 兼容)."""
    with open(out_path, 'w') as f:
        f.write("// IDMA SG cmd list (auto-gen by mesh_cmd.py, $readmemh 32-byte/cmd)\n")
        if header_lines:
            for line in header_lines:
                f.write(f"// {line}\n")
        f.write(f"// n_cmds = {len(cmds)}\n")
        for c in cmds:
            for hex_line in c.to_hex_lines():
                f.write(hex_line)
                if c.name and hex_line == c.to_hex_lines()[0]:
                    f.write(f"  // {c.name}{' [LAST]' if c.last_cmd else ''}")
                f.write("\n")
    return len(cmds)


@dataclass
class OdmaSgCmd:
    """[Phase 7 SMC + NUMA] ODMA SG cmd, 跟 odma_sg_dispatcher.sv 解码格式对齐
    (32 byte = 2 beats × 128-bit, 仅第 1 beat 有效, 16 byte):
      word 0:  dst_addr     [31:0]   目标全局地址 byte
      word 1:  btt          [22:0]   transfer 长度 byte (= sub_W × cout_slices × 16)
               last_cmd     [23]
               reserved     [31:24]
      word 2:  ofb_w_start  [15:0]   该段在 OFB SRAM 的起始 W 列 (NHWC gather 用)
               reserved     [31:16]
      word 3:  reserved
    """
    dst_addr:    int
    btt:         int
    ofb_w_start: int        # OFB SRAM 内段起始 W 列
    last_cmd:    bool = False
    name:        str = ""

    def to_hex_lines(self) -> list:
        word0 = self.dst_addr & 0xFFFFFFFF
        word1 = (self.btt & 0x7FFFFF) | ((1 << 23) if self.last_cmd else 0)
        word2 = self.ofb_w_start & 0xFFFF
        word3 = 0
        beat0 = (word0) | (word1 << 32) | (word2 << 64) | (word3 << 96)
        beat1 = 0
        return [f"{beat0:032x}", f"{beat1:032x}"]


def gen_odma_sg_cmd_list_w_slice(
    *,
    h_out:             int,                 # 该层 OFM 总行数
    cout_slices:       int,                 # cout / 16
    w_out_lo:          int,                 # 本核 OFM 起点列 (整图 W 坐标, 不含 halo)
    w_out_hi:          int,                 # 本核 OFM 终点列 (整图 W 坐标, 闭区间)
    seg_w_starts:      list,                # OFM 整图 W 段散布: 段 i 起点列
    seg_mem_bases:     list,                # 段 i 在 mem 内全局地址 base (byte)
    seg_widths:        list,                # 段 i 宽度
    ofb_w_offset_in_core: int = 0,          # 本核 OFB SRAM 内 W 起点 (一般 0, NHWC gather 从此列起)
) -> list:
    """
    生成 ConvCore[c] 的 ODMA SG cmd list (W slice 紧凑写到目标 mem 段).

    本核 OFM W 列范围 [w_out_lo, w_out_hi]. 跨整图 W 段时拆多条 cmd, 每条在一个
    mem 内的连续 burst write.
    每条 cmd 包含目标全局 byte 地址 + sub_W × cout_slices × 16 byte + ofb_w_start
    (本核 OFB SRAM 内对应段的起始 W 列).

    每行 OFM = N_seg_in_my_range 条 cmd. ofb_w_offset_in_core: 本核 OFB SRAM 内
    起始 W 列 (一般 0, 因为 ofb_writer 写本核 OFM 段从 col 0 开始).
    """
    n_segs = len(seg_w_starts)
    assert len(seg_mem_bases) == n_segs and len(seg_widths) == n_segs

    cmds = []
    for r in range(h_out):
        cur_w = w_out_lo
        while cur_w <= w_out_hi:
            # 找当前列在哪段
            seg_id = -1
            for s in range(n_segs):
                if seg_w_starts[s] <= cur_w < seg_w_starts[s] + seg_widths[s]:
                    seg_id = s
                    break
            if seg_id < 0:
                raise ValueError(f"col w={cur_w} not in any OFM segment")

            seg_w_end = seg_w_starts[seg_id] + seg_widths[seg_id] - 1
            chunk_lo = cur_w
            chunk_hi = min(w_out_hi, seg_w_end)
            chunk_cols = chunk_hi - chunk_lo + 1

            seg_w = seg_widths[seg_id]
            w_local_lo = chunk_lo - seg_w_starts[seg_id]
            byte_addr = (seg_mem_bases[seg_id]
                         + r * seg_w * cout_slices * 16
                         + w_local_lo * cout_slices * 16)
            chunk_btt = chunk_cols * cout_slices * 16

            # 本核 OFB SRAM 内对应该段的起始 W 列 (= chunk_lo - w_out_lo)
            ofb_w_start_in_core = ofb_w_offset_in_core + (chunk_lo - w_out_lo)

            cmds.append(OdmaSgCmd(
                dst_addr    = byte_addr,
                btt         = chunk_btt,
                ofb_w_start = ofb_w_start_in_core,
                last_cmd    = False,
                name        = f"r{r}_w[{chunk_lo}:{chunk_hi+1}]_seg{seg_id}",
            ))
            cur_w = chunk_hi + 1

    if cmds:
        cmds[-1].last_cmd = True
    return cmds


def write_odma_sg_cmd_list(out_path: str, cmds: list, header_lines: list = None) -> int:
    """写 ODMA SG cmd list 到 .hex 文件."""
    with open(out_path, 'w') as f:
        f.write("// ODMA SG cmd list (auto-gen by mesh_cmd.py, $readmemh 32-byte/cmd)\n")
        if header_lines:
            for line in header_lines:
                f.write(f"// {line}\n")
        f.write(f"// n_cmds = {len(cmds)}\n")
        for c in cmds:
            for hex_line in c.to_hex_lines():
                f.write(hex_line)
                if c.name and hex_line == c.to_hex_lines()[0]:
                    f.write(f"  // {c.name}{' [LAST]' if c.last_cmd else ''}")
                f.write("\n")
    return len(cmds)


# ============================================================================
# Phase 7 helper: 整图 W 4 等分散布到 4 mem (driver layout 决定)
# ============================================================================
def compute_smc_w_segments(W_full: int, n_mem: int) -> tuple:
    """整图 W 切 n_mem 段 (核间负载均衡: 余数分散给前 rem 个核, 每个 +1 列).

    Round-A optimization (2026-05-07): 旧版"余数全给末核"让 W_full=135 切 4 段 = [33,33,33,36],
    末核多 9% cells, layer barrier 让前 3 核闲等末核, util 损失 5~8%.
    新版"余数分散"让 W=135 = [34,34,34,33], 段宽差距 ≤ 1 col (3% vs 9%), 整网更均衡.

    跟 hw_files.compute_w_slice_geom 内 OFM 切法保持一致 (同公式):
      base = W_full // n; rem = W_full % n
      core[i] width = base+1 if i<rem else base
      core[i] start = i*(base+1) if i<rem else rem*(base+1) + (i-rem)*base

    例: W=135, n=4 → widths=[34,34,34,33], starts=[0,34,68,102]
        W=33,  n=4 → widths=[9,8,8,8],     starts=[0,9,17,25]
        W=32,  n=4 → widths=[8,8,8,8],     starts=[0,8,16,24]
    """
    base = W_full // n_mem
    rem  = W_full %  n_mem
    seg_widths  = [(base + 1) if i < rem else base for i in range(n_mem)]
    seg_w_starts = [0] * n_mem
    cur = 0
    for i in range(n_mem):
        seg_w_starts[i] = cur
        cur += seg_widths[i]
    return seg_w_starts, seg_widths


# ============================================================================
# Phase 6 兼容 (push 模式 mem cmd, 不变)
# ============================================================================
def gen_mem_ifb_push_cmds_w_slice(
    *,
    mem_id:           int,        # 哪个 mem core
    target_core_id:   int,        # 推送目标 ConvCore (mesh 模式 = mem_id)
    h_in:             int,        # 该层输入 H (整图)
    w_full:           int,        # 该层输入 W (整图)
    cin_slices:       int,        # cin / 16
    w_in_start:       int,        # 该核 IFM 起点列 (整图 x 坐标, 来自 compute_w_slice_geom)
    sub_w:            int,        # 该核 IFM 段长度 (含 halo)
    ifb_ddr_addr_w:   int,        # 整图 IFB 起点 (mem.ddr_mem 内 word offset, 整图坐标系)
    name_prefix:      str = "",
) -> List[MemCmd]:
    """
    生成 W slice 模式的 IFB row push cmd 序列.

    每行只推该核负责的 W 段 (sub_w 列, 含两侧 halo). IFB 整图 NHWC layout 假设:
      row r 起点 = ifb_ddr_addr_w + r * (w_full * cin_slices)
      该核段起点 = row 起点 + w_in_start * cin_slices
      该核段长度 = sub_w * cin_slices (word)

    每行一个 packet, ConvCore 端 ifb_axi_slave 自管 wptr (ring wrap), packet header
    sram_addr 字段不影响 ConvCore 写位置.

    -----------------------------------------------------------------------------
    [DDR layout 设计选择]
    每个 mem 当前仍按 "整图坐标 layout" 存储 IFB (即 mem[c].ddr_mem 整图位置都
    占用, 不是仅自己 W 段). 原因是 mesh 多层 chain 下:
      - 上层 ConvCore[c] OFM 写位置 = ConvCore.bus_aw.awaddr 用整图 stride 算出
        的 (整图坐标 W 段位置), 不是 mem 内紧凑坐标
      - 下层 mem[c] cmd 拉 IFB 时 ddr_addr_w 必须指向上层 OFM 的整图坐标位置,
        否则读不到数据
    所以 mem 内整图坐标 layout 是 mesh chain 协议的硬约束, 不是冗余.

    实际硬件部署优化空间 (driver 视角):
      - 多 DDR 端口下, 每个 DDR 物理上只装自己 W 段 (整图坐标 layout 下其他段
        位置不分配物理存储, 类似稀疏 DDR)
      - sim 用 modelsim 的 sparse memory 行为 (没写过的 word 不占内存), broadcast
        TB 实际内存占用 ≈ 4× (写过段) 而不是 4× 整图
      - root layer (e.g. layer 0 IFB, 没有 OFM 来源) 可单独优化为 W 段紧凑, 但
        当前 driver 没区分, 统一走整图坐标保持代码简洁
    -----------------------------------------------------------------------------
    """
    row_words_full = w_full * cin_slices
    burst_w = sub_w * cin_slices
    cmds: List[MemCmd] = []
    tdest = conv_core_tdest(target_core_id)
    for r in range(h_in):
        addr_w = ifb_ddr_addr_w + r * row_words_full + w_in_start * cin_slices
        cmds.append(MemCmd(
            ddr_addr_w    = addr_w,
            burst_len     = burst_w,
            sram_offset_w = addr_w,    # stub 限制 sram_offset == ddr_addr
            tdest         = tdest,
            opcode        = OPCODE_WRITE_IFB,
            name          = f"{name_prefix}row{r}",
        ))
    return cmds
